services:
  nginx:
    image: nginx:1.27-alpine
    container_name: tivix-front-nginx
    restart: unless-stopped
    networks:
      - web
      - internal-services
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tivix-front.rule=Host(`tivix.com.br`) || Host(`www.tivix.com.br`)"
      - "traefik.http.routers.tivix-front.entrypoints=websecure"
      - "traefik.http.routers.tivix-front.tls.certresolver=myresolver"
      - "traefik.http.routers.tivix-front.service=tivix-front-service"
      - "traefik.http.services.tivix-front-service.loadbalancer.server.port=80"

  app:
    image: ghcr.io/rdemora2/front-site--tivix-technologies:latest
    container_name: tivix-front-app
    restart: unless-stopped
    networks:
      - internal-services

networks:
  web:
    external: true
  internal-services:
    external: true
